// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package maglev

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type maglevLookupBackendKey struct {
	_  structs.HostLayout
	Id uint32
}

type maglevLookupBackendValue struct {
	_    structs.HostLayout
	Addr uint32
	Port uint16
	Pad  uint16
}

type maglevLookupMaglevEntry struct {
	_         structs.HostLayout
	BackendId uint32
}

// loadMaglevLookup returns the embedded CollectionSpec for maglevLookup.
func loadMaglevLookup() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MaglevLookupBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load maglevLookup: %w", err)
	}

	return spec, err
}

// loadMaglevLookupObjects loads maglevLookup and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*maglevLookupObjects
//	*maglevLookupPrograms
//	*maglevLookupMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMaglevLookupObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMaglevLookup()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// maglevLookupSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type maglevLookupSpecs struct {
	maglevLookupProgramSpecs
	maglevLookupMapSpecs
	maglevLookupVariableSpecs
}

// maglevLookupProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type maglevLookupProgramSpecs struct {
	MaglevXdpProg *ebpf.ProgramSpec `ebpf:"maglev_xdp_prog"`
}

// maglevLookupMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type maglevLookupMapSpecs struct {
	MaglevBackends *ebpf.MapSpec `ebpf:"maglev_backends"`
	MaglevInner    *ebpf.MapSpec `ebpf:"maglev_inner"`
	MaglevOuter    *ebpf.MapSpec `ebpf:"maglev_outer"`
	MaglevStats    *ebpf.MapSpec `ebpf:"maglev_stats"`
}

// maglevLookupVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type maglevLookupVariableSpecs struct {
}

// maglevLookupObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMaglevLookupObjects or ebpf.CollectionSpec.LoadAndAssign.
type maglevLookupObjects struct {
	maglevLookupPrograms
	maglevLookupMaps
	maglevLookupVariables
}

func (o *maglevLookupObjects) Close() error {
	return _MaglevLookupClose(
		&o.maglevLookupPrograms,
		&o.maglevLookupMaps,
	)
}

// maglevLookupMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMaglevLookupObjects or ebpf.CollectionSpec.LoadAndAssign.
type maglevLookupMaps struct {
	MaglevBackends *ebpf.Map `ebpf:"maglev_backends"`
	MaglevInner    *ebpf.Map `ebpf:"maglev_inner"`
	MaglevOuter    *ebpf.Map `ebpf:"maglev_outer"`
	MaglevStats    *ebpf.Map `ebpf:"maglev_stats"`
}

func (m *maglevLookupMaps) Close() error {
	return _MaglevLookupClose(
		m.MaglevBackends,
		m.MaglevInner,
		m.MaglevOuter,
		m.MaglevStats,
	)
}

// maglevLookupVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMaglevLookupObjects or ebpf.CollectionSpec.LoadAndAssign.
type maglevLookupVariables struct {
}

// maglevLookupPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMaglevLookupObjects or ebpf.CollectionSpec.LoadAndAssign.
type maglevLookupPrograms struct {
	MaglevXdpProg *ebpf.Program `ebpf:"maglev_xdp_prog"`
}

func (p *maglevLookupPrograms) Close() error {
	return _MaglevLookupClose(
		p.MaglevXdpProg,
	)
}

func _MaglevLookupClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed maglevlookup_bpfel.o
var _MaglevLookupBytes []byte
