apiVersion: v2
name: novaedge-agent
description: NovaEdge Agent for remote/edge cluster deployments in a hub-spoke architecture
type: application
version: 0.1.0
appVersion: "v1.7.7"
keywords:
  - novaedge
  - load-balancer
  - proxy
  - agent
  - edge
  - multi-cluster
home: https://github.com/azrtydxb/novaedge
sources:
  - https://github.com/azrtydxb/novaedge
maintainers:
  - name: azrtydxb
    email: pascal@novaedge.io
icon: https://raw.githubusercontent.com/azrtydxb/novaedge/main/docs/logo.png
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: networking
