apiVersion: v2
name: novaedge-agent
description: NovaEdge Agent for remote/edge cluster deployments in a hub-spoke architecture
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - novaedge
  - load-balancer
  - proxy
  - agent
  - edge
  - multi-cluster
home: https://github.com/azrtydxb/novaedge
sources:
  - https://github.com/azrtydxb/novaedge
maintainers:
  - name: NovaEdge Authors
    url: https://github.com/azrtydxb/novaedge
annotations:
  category: Networking
