// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package afxdp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type afxdpRedirectVipKey struct {
	_     structs.HostLayout
	Addr  uint32
	Port  uint16
	Proto uint8
	Pad   uint8
}

// loadAfxdpRedirect returns the embedded CollectionSpec for afxdpRedirect.
func loadAfxdpRedirect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AfxdpRedirectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load afxdpRedirect: %w", err)
	}

	return spec, err
}

// loadAfxdpRedirectObjects loads afxdpRedirect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*afxdpRedirectObjects
//	*afxdpRedirectPrograms
//	*afxdpRedirectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAfxdpRedirectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAfxdpRedirect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// afxdpRedirectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type afxdpRedirectSpecs struct {
	afxdpRedirectProgramSpecs
	afxdpRedirectMapSpecs
	afxdpRedirectVariableSpecs
}

// afxdpRedirectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type afxdpRedirectProgramSpecs struct {
	AfxdpRedirectProg *ebpf.ProgramSpec `ebpf:"afxdp_redirect_prog"`
}

// afxdpRedirectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type afxdpRedirectMapSpecs struct {
	AfxdpStats *ebpf.MapSpec `ebpf:"afxdp_stats"`
	AfxdpVips  *ebpf.MapSpec `ebpf:"afxdp_vips"`
	XskMap     *ebpf.MapSpec `ebpf:"xsk_map"`
}

// afxdpRedirectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type afxdpRedirectVariableSpecs struct {
}

// afxdpRedirectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAfxdpRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type afxdpRedirectObjects struct {
	afxdpRedirectPrograms
	afxdpRedirectMaps
	afxdpRedirectVariables
}

func (o *afxdpRedirectObjects) Close() error {
	return _AfxdpRedirectClose(
		&o.afxdpRedirectPrograms,
		&o.afxdpRedirectMaps,
	)
}

// afxdpRedirectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAfxdpRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type afxdpRedirectMaps struct {
	AfxdpStats *ebpf.Map `ebpf:"afxdp_stats"`
	AfxdpVips  *ebpf.Map `ebpf:"afxdp_vips"`
	XskMap     *ebpf.Map `ebpf:"xsk_map"`
}

func (m *afxdpRedirectMaps) Close() error {
	return _AfxdpRedirectClose(
		m.AfxdpStats,
		m.AfxdpVips,
		m.XskMap,
	)
}

// afxdpRedirectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAfxdpRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type afxdpRedirectVariables struct {
}

// afxdpRedirectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAfxdpRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type afxdpRedirectPrograms struct {
	AfxdpRedirectProg *ebpf.Program `ebpf:"afxdp_redirect_prog"`
}

func (p *afxdpRedirectPrograms) Close() error {
	return _AfxdpRedirectClose(
		p.AfxdpRedirectProg,
	)
}

func _AfxdpRedirectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed afxdpredirect_bpfel.o
var _AfxdpRedirectBytes []byte
