// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: dataplane.proto

package dataplane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataplaneControl_ApplyConfig_FullMethodName        = "/novaedge.dataplane.v1.DataplaneControl/ApplyConfig"
	DataplaneControl_UpsertGateway_FullMethodName      = "/novaedge.dataplane.v1.DataplaneControl/UpsertGateway"
	DataplaneControl_DeleteGateway_FullMethodName      = "/novaedge.dataplane.v1.DataplaneControl/DeleteGateway"
	DataplaneControl_UpsertRoute_FullMethodName        = "/novaedge.dataplane.v1.DataplaneControl/UpsertRoute"
	DataplaneControl_DeleteRoute_FullMethodName        = "/novaedge.dataplane.v1.DataplaneControl/DeleteRoute"
	DataplaneControl_UpsertCluster_FullMethodName      = "/novaedge.dataplane.v1.DataplaneControl/UpsertCluster"
	DataplaneControl_DeleteCluster_FullMethodName      = "/novaedge.dataplane.v1.DataplaneControl/DeleteCluster"
	DataplaneControl_UpsertVIP_FullMethodName          = "/novaedge.dataplane.v1.DataplaneControl/UpsertVIP"
	DataplaneControl_DeleteVIP_FullMethodName          = "/novaedge.dataplane.v1.DataplaneControl/DeleteVIP"
	DataplaneControl_UpsertL4Listener_FullMethodName   = "/novaedge.dataplane.v1.DataplaneControl/UpsertL4Listener"
	DataplaneControl_DeleteL4Listener_FullMethodName   = "/novaedge.dataplane.v1.DataplaneControl/DeleteL4Listener"
	DataplaneControl_UpsertPolicy_FullMethodName       = "/novaedge.dataplane.v1.DataplaneControl/UpsertPolicy"
	DataplaneControl_DeletePolicy_FullMethodName       = "/novaedge.dataplane.v1.DataplaneControl/DeletePolicy"
	DataplaneControl_UpsertMeshConfig_FullMethodName   = "/novaedge.dataplane.v1.DataplaneControl/UpsertMeshConfig"
	DataplaneControl_DeleteMeshConfig_FullMethodName   = "/novaedge.dataplane.v1.DataplaneControl/DeleteMeshConfig"
	DataplaneControl_UpsertWANLink_FullMethodName      = "/novaedge.dataplane.v1.DataplaneControl/UpsertWANLink"
	DataplaneControl_DeleteWANLink_FullMethodName      = "/novaedge.dataplane.v1.DataplaneControl/DeleteWANLink"
	DataplaneControl_AttachProgram_FullMethodName      = "/novaedge.dataplane.v1.DataplaneControl/AttachProgram"
	DataplaneControl_DetachProgram_FullMethodName      = "/novaedge.dataplane.v1.DataplaneControl/DetachProgram"
	DataplaneControl_StreamFlows_FullMethodName        = "/novaedge.dataplane.v1.DataplaneControl/StreamFlows"
	DataplaneControl_GetDataplaneStatus_FullMethodName = "/novaedge.dataplane.v1.DataplaneControl/GetDataplaneStatus"
	DataplaneControl_StreamMetrics_FullMethodName      = "/novaedge.dataplane.v1.DataplaneControl/StreamMetrics"
)

// DataplaneControlClient is the client API for DataplaneControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataplaneControl is the gRPC service for agent→dataplane communication.
// The Go agent pushes configuration to the Rust dataplane daemon over a
// Unix domain socket. The dataplane manages eBPF programs, L4/L7 forwarding,
// VIP operations, and observability telemetry.
type DataplaneControlClient interface {
	// ── Full config push ─────────────────────────────────────────────────
	// ApplyConfig pushes a full configuration snapshot to the dataplane.
	// The dataplane atomically replaces its running config with the snapshot.
	ApplyConfig(ctx context.Context, in *ApplyConfigRequest, opts ...grpc.CallOption) (*ApplyConfigResponse, error)
	// ── Gateway / Listener management ────────────────────────────────────
	// UpsertGateway creates or updates an HTTP/HTTPS/HTTP3/TCP/UDP listener.
	UpsertGateway(ctx context.Context, in *UpsertGatewayRequest, opts ...grpc.CallOption) (*UpsertGatewayResponse, error)
	// DeleteGateway removes a listener by name.
	DeleteGateway(ctx context.Context, in *DeleteGatewayRequest, opts ...grpc.CallOption) (*DeleteGatewayResponse, error)
	// ── L7 Route management ──────────────────────────────────────────────
	// UpsertRoute creates or updates an L7 routing rule.
	UpsertRoute(ctx context.Context, in *UpsertRouteRequest, opts ...grpc.CallOption) (*UpsertRouteResponse, error)
	// DeleteRoute removes a route by name.
	DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error)
	// ── Backend cluster management ───────────────────────────────────────
	// UpsertCluster creates or updates a backend cluster (endpoint list,
	// load balancing, health check, circuit breaker).
	UpsertCluster(ctx context.Context, in *UpsertClusterRequest, opts ...grpc.CallOption) (*UpsertClusterResponse, error)
	// DeleteCluster removes a backend cluster by name.
	DeleteCluster(ctx context.Context, in *DeleteClusterRequest, opts ...grpc.CallOption) (*DeleteClusterResponse, error)
	// ── VIP management ───────────────────────────────────────────────────
	// UpsertVIP creates or updates a Virtual IP address.
	UpsertVIP(ctx context.Context, in *UpsertVIPRequest, opts ...grpc.CallOption) (*UpsertVIPResponse, error)
	// DeleteVIP removes a VIP by name.
	DeleteVIP(ctx context.Context, in *DeleteVIPRequest, opts ...grpc.CallOption) (*DeleteVIPResponse, error)
	// ── L4 Listener management ──────────────────────────────────────────
	// UpsertL4Listener creates or updates a TCP/UDP/TLS passthrough listener.
	UpsertL4Listener(ctx context.Context, in *UpsertL4ListenerRequest, opts ...grpc.CallOption) (*UpsertL4ListenerResponse, error)
	// DeleteL4Listener removes an L4 listener by name.
	DeleteL4Listener(ctx context.Context, in *DeleteL4ListenerRequest, opts ...grpc.CallOption) (*DeleteL4ListenerResponse, error)
	// ── Policy management ────────────────────────────────────────────────
	// UpsertPolicy creates or updates a typed policy (rate-limit, auth, WAF, etc.).
	UpsertPolicy(ctx context.Context, in *UpsertPolicyRequest, opts ...grpc.CallOption) (*UpsertPolicyResponse, error)
	// DeletePolicy removes a policy by name.
	DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*DeletePolicyResponse, error)
	// ── Mesh config ──────────────────────────────────────────────────────
	// UpsertMeshConfig creates or updates the service-mesh configuration.
	UpsertMeshConfig(ctx context.Context, in *UpsertMeshConfigRequest, opts ...grpc.CallOption) (*UpsertMeshConfigResponse, error)
	// DeleteMeshConfig removes the mesh configuration.
	DeleteMeshConfig(ctx context.Context, in *DeleteMeshConfigRequest, opts ...grpc.CallOption) (*DeleteMeshConfigResponse, error)
	// ── SD-WAN ───────────────────────────────────────────────────────────
	// UpsertWANLink creates or updates a WAN link.
	UpsertWANLink(ctx context.Context, in *UpsertWANLinkRequest, opts ...grpc.CallOption) (*UpsertWANLinkResponse, error)
	// DeleteWANLink removes a WAN link by name.
	DeleteWANLink(ctx context.Context, in *DeleteWANLinkRequest, opts ...grpc.CallOption) (*DeleteWANLinkResponse, error)
	// ── eBPF lifecycle ───────────────────────────────────────────────────
	// AttachProgram loads and attaches an eBPF program.
	AttachProgram(ctx context.Context, in *AttachProgramRequest, opts ...grpc.CallOption) (*AttachProgramResponse, error)
	// DetachProgram detaches and unloads an eBPF program.
	DetachProgram(ctx context.Context, in *DetachProgramRequest, opts ...grpc.CallOption) (*DetachProgramResponse, error)
	// ── Observability ────────────────────────────────────────────────────
	// StreamFlows streams flow events captured from the eBPF ring buffer.
	StreamFlows(ctx context.Context, in *StreamFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowEvent], error)
	// GetDataplaneStatus returns the current dataplane status.
	GetDataplaneStatus(ctx context.Context, in *GetDataplaneStatusRequest, opts ...grpc.CallOption) (*DataplaneStatus, error)
	// StreamMetrics streams periodic metrics snapshots from the dataplane.
	StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsSnapshot], error)
}

type dataplaneControlClient struct {
	cc grpc.ClientConnInterface
}

func NewDataplaneControlClient(cc grpc.ClientConnInterface) DataplaneControlClient {
	return &dataplaneControlClient{cc}
}

func (c *dataplaneControlClient) ApplyConfig(ctx context.Context, in *ApplyConfigRequest, opts ...grpc.CallOption) (*ApplyConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyConfigResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_ApplyConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertGateway(ctx context.Context, in *UpsertGatewayRequest, opts ...grpc.CallOption) (*UpsertGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertGatewayResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteGateway(ctx context.Context, in *DeleteGatewayRequest, opts ...grpc.CallOption) (*DeleteGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGatewayResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertRoute(ctx context.Context, in *UpsertRouteRequest, opts ...grpc.CallOption) (*UpsertRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertRouteResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertCluster(ctx context.Context, in *UpsertClusterRequest, opts ...grpc.CallOption) (*UpsertClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertClusterResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteCluster(ctx context.Context, in *DeleteClusterRequest, opts ...grpc.CallOption) (*DeleteClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteClusterResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertVIP(ctx context.Context, in *UpsertVIPRequest, opts ...grpc.CallOption) (*UpsertVIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertVIPResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertVIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteVIP(ctx context.Context, in *DeleteVIPRequest, opts ...grpc.CallOption) (*DeleteVIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVIPResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteVIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertL4Listener(ctx context.Context, in *UpsertL4ListenerRequest, opts ...grpc.CallOption) (*UpsertL4ListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertL4ListenerResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertL4Listener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteL4Listener(ctx context.Context, in *DeleteL4ListenerRequest, opts ...grpc.CallOption) (*DeleteL4ListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteL4ListenerResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteL4Listener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertPolicy(ctx context.Context, in *UpsertPolicyRequest, opts ...grpc.CallOption) (*UpsertPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertPolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*DeletePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeletePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertMeshConfig(ctx context.Context, in *UpsertMeshConfigRequest, opts ...grpc.CallOption) (*UpsertMeshConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertMeshConfigResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertMeshConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteMeshConfig(ctx context.Context, in *DeleteMeshConfigRequest, opts ...grpc.CallOption) (*DeleteMeshConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMeshConfigResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteMeshConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertWANLink(ctx context.Context, in *UpsertWANLinkRequest, opts ...grpc.CallOption) (*UpsertWANLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertWANLinkResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertWANLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteWANLink(ctx context.Context, in *DeleteWANLinkRequest, opts ...grpc.CallOption) (*DeleteWANLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWANLinkResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteWANLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) AttachProgram(ctx context.Context, in *AttachProgramRequest, opts ...grpc.CallOption) (*AttachProgramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachProgramResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_AttachProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DetachProgram(ctx context.Context, in *DetachProgramRequest, opts ...grpc.CallOption) (*DetachProgramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachProgramResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DetachProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) StreamFlows(ctx context.Context, in *StreamFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataplaneControl_ServiceDesc.Streams[0], DataplaneControl_StreamFlows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFlowsRequest, FlowEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneControl_StreamFlowsClient = grpc.ServerStreamingClient[FlowEvent]

func (c *dataplaneControlClient) GetDataplaneStatus(ctx context.Context, in *GetDataplaneStatusRequest, opts ...grpc.CallOption) (*DataplaneStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataplaneStatus)
	err := c.cc.Invoke(ctx, DataplaneControl_GetDataplaneStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataplaneControl_ServiceDesc.Streams[1], DataplaneControl_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMetricsRequest, MetricsSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneControl_StreamMetricsClient = grpc.ServerStreamingClient[MetricsSnapshot]

// DataplaneControlServer is the server API for DataplaneControl service.
// All implementations must embed UnimplementedDataplaneControlServer
// for forward compatibility.
//
// DataplaneControl is the gRPC service for agent→dataplane communication.
// The Go agent pushes configuration to the Rust dataplane daemon over a
// Unix domain socket. The dataplane manages eBPF programs, L4/L7 forwarding,
// VIP operations, and observability telemetry.
type DataplaneControlServer interface {
	// ── Full config push ─────────────────────────────────────────────────
	// ApplyConfig pushes a full configuration snapshot to the dataplane.
	// The dataplane atomically replaces its running config with the snapshot.
	ApplyConfig(context.Context, *ApplyConfigRequest) (*ApplyConfigResponse, error)
	// ── Gateway / Listener management ────────────────────────────────────
	// UpsertGateway creates or updates an HTTP/HTTPS/HTTP3/TCP/UDP listener.
	UpsertGateway(context.Context, *UpsertGatewayRequest) (*UpsertGatewayResponse, error)
	// DeleteGateway removes a listener by name.
	DeleteGateway(context.Context, *DeleteGatewayRequest) (*DeleteGatewayResponse, error)
	// ── L7 Route management ──────────────────────────────────────────────
	// UpsertRoute creates or updates an L7 routing rule.
	UpsertRoute(context.Context, *UpsertRouteRequest) (*UpsertRouteResponse, error)
	// DeleteRoute removes a route by name.
	DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error)
	// ── Backend cluster management ───────────────────────────────────────
	// UpsertCluster creates or updates a backend cluster (endpoint list,
	// load balancing, health check, circuit breaker).
	UpsertCluster(context.Context, *UpsertClusterRequest) (*UpsertClusterResponse, error)
	// DeleteCluster removes a backend cluster by name.
	DeleteCluster(context.Context, *DeleteClusterRequest) (*DeleteClusterResponse, error)
	// ── VIP management ───────────────────────────────────────────────────
	// UpsertVIP creates or updates a Virtual IP address.
	UpsertVIP(context.Context, *UpsertVIPRequest) (*UpsertVIPResponse, error)
	// DeleteVIP removes a VIP by name.
	DeleteVIP(context.Context, *DeleteVIPRequest) (*DeleteVIPResponse, error)
	// ── L4 Listener management ──────────────────────────────────────────
	// UpsertL4Listener creates or updates a TCP/UDP/TLS passthrough listener.
	UpsertL4Listener(context.Context, *UpsertL4ListenerRequest) (*UpsertL4ListenerResponse, error)
	// DeleteL4Listener removes an L4 listener by name.
	DeleteL4Listener(context.Context, *DeleteL4ListenerRequest) (*DeleteL4ListenerResponse, error)
	// ── Policy management ────────────────────────────────────────────────
	// UpsertPolicy creates or updates a typed policy (rate-limit, auth, WAF, etc.).
	UpsertPolicy(context.Context, *UpsertPolicyRequest) (*UpsertPolicyResponse, error)
	// DeletePolicy removes a policy by name.
	DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error)
	// ── Mesh config ──────────────────────────────────────────────────────
	// UpsertMeshConfig creates or updates the service-mesh configuration.
	UpsertMeshConfig(context.Context, *UpsertMeshConfigRequest) (*UpsertMeshConfigResponse, error)
	// DeleteMeshConfig removes the mesh configuration.
	DeleteMeshConfig(context.Context, *DeleteMeshConfigRequest) (*DeleteMeshConfigResponse, error)
	// ── SD-WAN ───────────────────────────────────────────────────────────
	// UpsertWANLink creates or updates a WAN link.
	UpsertWANLink(context.Context, *UpsertWANLinkRequest) (*UpsertWANLinkResponse, error)
	// DeleteWANLink removes a WAN link by name.
	DeleteWANLink(context.Context, *DeleteWANLinkRequest) (*DeleteWANLinkResponse, error)
	// ── eBPF lifecycle ───────────────────────────────────────────────────
	// AttachProgram loads and attaches an eBPF program.
	AttachProgram(context.Context, *AttachProgramRequest) (*AttachProgramResponse, error)
	// DetachProgram detaches and unloads an eBPF program.
	DetachProgram(context.Context, *DetachProgramRequest) (*DetachProgramResponse, error)
	// ── Observability ────────────────────────────────────────────────────
	// StreamFlows streams flow events captured from the eBPF ring buffer.
	StreamFlows(*StreamFlowsRequest, grpc.ServerStreamingServer[FlowEvent]) error
	// GetDataplaneStatus returns the current dataplane status.
	GetDataplaneStatus(context.Context, *GetDataplaneStatusRequest) (*DataplaneStatus, error)
	// StreamMetrics streams periodic metrics snapshots from the dataplane.
	StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[MetricsSnapshot]) error
	mustEmbedUnimplementedDataplaneControlServer()
}

// UnimplementedDataplaneControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataplaneControlServer struct{}

func (UnimplementedDataplaneControlServer) ApplyConfig(context.Context, *ApplyConfigRequest) (*ApplyConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyConfig not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertGateway(context.Context, *UpsertGatewayRequest) (*UpsertGatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertGateway not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteGateway(context.Context, *DeleteGatewayRequest) (*DeleteGatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGateway not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertRoute(context.Context, *UpsertRouteRequest) (*UpsertRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertRoute not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertCluster(context.Context, *UpsertClusterRequest) (*UpsertClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertCluster not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteCluster(context.Context, *DeleteClusterRequest) (*DeleteClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCluster not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertVIP(context.Context, *UpsertVIPRequest) (*UpsertVIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertVIP not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteVIP(context.Context, *DeleteVIPRequest) (*DeleteVIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVIP not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertL4Listener(context.Context, *UpsertL4ListenerRequest) (*UpsertL4ListenerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertL4Listener not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteL4Listener(context.Context, *DeleteL4ListenerRequest) (*DeleteL4ListenerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteL4Listener not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertPolicy(context.Context, *UpsertPolicyRequest) (*UpsertPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertPolicy not implemented")
}
func (UnimplementedDataplaneControlServer) DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePolicy not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertMeshConfig(context.Context, *UpsertMeshConfigRequest) (*UpsertMeshConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertMeshConfig not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteMeshConfig(context.Context, *DeleteMeshConfigRequest) (*DeleteMeshConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMeshConfig not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertWANLink(context.Context, *UpsertWANLinkRequest) (*UpsertWANLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertWANLink not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteWANLink(context.Context, *DeleteWANLinkRequest) (*DeleteWANLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWANLink not implemented")
}
func (UnimplementedDataplaneControlServer) AttachProgram(context.Context, *AttachProgramRequest) (*AttachProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachProgram not implemented")
}
func (UnimplementedDataplaneControlServer) DetachProgram(context.Context, *DetachProgramRequest) (*DetachProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetachProgram not implemented")
}
func (UnimplementedDataplaneControlServer) StreamFlows(*StreamFlowsRequest, grpc.ServerStreamingServer[FlowEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamFlows not implemented")
}
func (UnimplementedDataplaneControlServer) GetDataplaneStatus(context.Context, *GetDataplaneStatusRequest) (*DataplaneStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataplaneStatus not implemented")
}
func (UnimplementedDataplaneControlServer) StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[MetricsSnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedDataplaneControlServer) mustEmbedUnimplementedDataplaneControlServer() {}
func (UnimplementedDataplaneControlServer) testEmbeddedByValue()                          {}

// UnsafeDataplaneControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataplaneControlServer will
// result in compilation errors.
type UnsafeDataplaneControlServer interface {
	mustEmbedUnimplementedDataplaneControlServer()
}

func RegisterDataplaneControlServer(s grpc.ServiceRegistrar, srv DataplaneControlServer) {
	// If the following call pancis, it indicates UnimplementedDataplaneControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataplaneControl_ServiceDesc, srv)
}

func _DataplaneControl_ApplyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).ApplyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_ApplyConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).ApplyConfig(ctx, req.(*ApplyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertGateway(ctx, req.(*UpsertGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteGateway(ctx, req.(*DeleteGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertRoute(ctx, req.(*UpsertRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteRoute(ctx, req.(*DeleteRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertCluster(ctx, req.(*UpsertClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteCluster(ctx, req.(*DeleteClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertVIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertVIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertVIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertVIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertVIP(ctx, req.(*UpsertVIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteVIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteVIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteVIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteVIP(ctx, req.(*DeleteVIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertL4Listener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertL4ListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertL4Listener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertL4Listener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertL4Listener(ctx, req.(*UpsertL4ListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteL4Listener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteL4ListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteL4Listener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteL4Listener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteL4Listener(ctx, req.(*DeleteL4ListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertPolicy(ctx, req.(*UpsertPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeletePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeletePolicy(ctx, req.(*DeletePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertMeshConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertMeshConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertMeshConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertMeshConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertMeshConfig(ctx, req.(*UpsertMeshConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteMeshConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMeshConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteMeshConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteMeshConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteMeshConfig(ctx, req.(*DeleteMeshConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertWANLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertWANLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertWANLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertWANLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertWANLink(ctx, req.(*UpsertWANLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteWANLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWANLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteWANLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteWANLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteWANLink(ctx, req.(*DeleteWANLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_AttachProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).AttachProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_AttachProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).AttachProgram(ctx, req.(*AttachProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DetachProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DetachProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DetachProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DetachProgram(ctx, req.(*DetachProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_StreamFlows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamFlowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataplaneControlServer).StreamFlows(m, &grpc.GenericServerStream[StreamFlowsRequest, FlowEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneControl_StreamFlowsServer = grpc.ServerStreamingServer[FlowEvent]

func _DataplaneControl_GetDataplaneStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataplaneStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).GetDataplaneStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_GetDataplaneStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).GetDataplaneStatus(ctx, req.(*GetDataplaneStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataplaneControlServer).StreamMetrics(m, &grpc.GenericServerStream[StreamMetricsRequest, MetricsSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneControl_StreamMetricsServer = grpc.ServerStreamingServer[MetricsSnapshot]

// DataplaneControl_ServiceDesc is the grpc.ServiceDesc for DataplaneControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataplaneControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novaedge.dataplane.v1.DataplaneControl",
	HandlerType: (*DataplaneControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyConfig",
			Handler:    _DataplaneControl_ApplyConfig_Handler,
		},
		{
			MethodName: "UpsertGateway",
			Handler:    _DataplaneControl_UpsertGateway_Handler,
		},
		{
			MethodName: "DeleteGateway",
			Handler:    _DataplaneControl_DeleteGateway_Handler,
		},
		{
			MethodName: "UpsertRoute",
			Handler:    _DataplaneControl_UpsertRoute_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _DataplaneControl_DeleteRoute_Handler,
		},
		{
			MethodName: "UpsertCluster",
			Handler:    _DataplaneControl_UpsertCluster_Handler,
		},
		{
			MethodName: "DeleteCluster",
			Handler:    _DataplaneControl_DeleteCluster_Handler,
		},
		{
			MethodName: "UpsertVIP",
			Handler:    _DataplaneControl_UpsertVIP_Handler,
		},
		{
			MethodName: "DeleteVIP",
			Handler:    _DataplaneControl_DeleteVIP_Handler,
		},
		{
			MethodName: "UpsertL4Listener",
			Handler:    _DataplaneControl_UpsertL4Listener_Handler,
		},
		{
			MethodName: "DeleteL4Listener",
			Handler:    _DataplaneControl_DeleteL4Listener_Handler,
		},
		{
			MethodName: "UpsertPolicy",
			Handler:    _DataplaneControl_UpsertPolicy_Handler,
		},
		{
			MethodName: "DeletePolicy",
			Handler:    _DataplaneControl_DeletePolicy_Handler,
		},
		{
			MethodName: "UpsertMeshConfig",
			Handler:    _DataplaneControl_UpsertMeshConfig_Handler,
		},
		{
			MethodName: "DeleteMeshConfig",
			Handler:    _DataplaneControl_DeleteMeshConfig_Handler,
		},
		{
			MethodName: "UpsertWANLink",
			Handler:    _DataplaneControl_UpsertWANLink_Handler,
		},
		{
			MethodName: "DeleteWANLink",
			Handler:    _DataplaneControl_DeleteWANLink_Handler,
		},
		{
			MethodName: "AttachProgram",
			Handler:    _DataplaneControl_AttachProgram_Handler,
		},
		{
			MethodName: "DetachProgram",
			Handler:    _DataplaneControl_DetachProgram_Handler,
		},
		{
			MethodName: "GetDataplaneStatus",
			Handler:    _DataplaneControl_GetDataplaneStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFlows",
			Handler:       _DataplaneControl_StreamFlows_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamMetrics",
			Handler:       _DataplaneControl_StreamMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dataplane.proto",
}
