apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: novaedge-webui-rolebinding
  labels:
    app.kubernetes.io/name: novaedge-webui
    app.kubernetes.io/component: webui
    app.kubernetes.io/part-of: novaedge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: novaedge-webui-role
subjects:
- kind: ServiceAccount
  name: novaedge-webui
  namespace: nova-system
