//! Generated protobuf types and gRPC service definitions.
//!
//! This module includes the code generated by `tonic-build` from
//! `api/proto/dataplane.proto`.

#![allow(clippy::derive_partial_eq_without_eq)]

tonic::include_proto!("novaedge.dataplane.v1");
