// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package conntrack

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type conntrackCtEntry struct {
	_           structs.HostLayout
	BackendIp   uint32
	BackendPort uint16
	State       uint8
	Pad         uint8
	Timestamp   uint64
	RxBytes     uint64
	TxBytes     uint64
}

type conntrackCtKey struct {
	_       structs.HostLayout
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	Pad     [3]uint8
}

// loadConntrack returns the embedded CollectionSpec for conntrack.
func loadConntrack() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConntrackBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load conntrack: %w", err)
	}

	return spec, err
}

// loadConntrackObjects loads conntrack and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*conntrackObjects
//	*conntrackPrograms
//	*conntrackMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConntrackObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConntrack()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// conntrackSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type conntrackSpecs struct {
	conntrackProgramSpecs
	conntrackMapSpecs
	conntrackVariableSpecs
}

// conntrackProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type conntrackProgramSpecs struct {
	CtXdpProg *ebpf.ProgramSpec `ebpf:"ct_xdp_prog"`
}

// conntrackMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type conntrackMapSpecs struct {
	CtStats    *ebpf.MapSpec `ebpf:"ct_stats"`
	NovaedgeCt *ebpf.MapSpec `ebpf:"novaedge_ct"`
}

// conntrackVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type conntrackVariableSpecs struct {
}

// conntrackObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type conntrackObjects struct {
	conntrackPrograms
	conntrackMaps
	conntrackVariables
}

func (o *conntrackObjects) Close() error {
	return _ConntrackClose(
		&o.conntrackPrograms,
		&o.conntrackMaps,
	)
}

// conntrackMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type conntrackMaps struct {
	CtStats    *ebpf.Map `ebpf:"ct_stats"`
	NovaedgeCt *ebpf.Map `ebpf:"novaedge_ct"`
}

func (m *conntrackMaps) Close() error {
	return _ConntrackClose(
		m.CtStats,
		m.NovaedgeCt,
	)
}

// conntrackVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type conntrackVariables struct {
}

// conntrackPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type conntrackPrograms struct {
	CtXdpProg *ebpf.Program `ebpf:"ct_xdp_prog"`
}

func (p *conntrackPrograms) Close() error {
	return _ConntrackClose(
		p.CtXdpProg,
	)
}

func _ConntrackClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed conntrack_bpfel.o
var _ConntrackBytes []byte
