{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "novaedge-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "novaedge-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "novaedge-agent.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
