apiVersion: v2
name: novaedge
description: A Helm chart for NovaEdge - Kubernetes-native distributed load balancer, reverse proxy, and VIP controller
type: application
version: 0.1.0
appVersion: "v1.7.4"
keywords:
- load-balancer
- ingress
- proxy
- kubernetes
- gateway
- vip
home: https://github.com/azrtydxb/novaedge
sources:
- https://github.com/azrtydxb/novaedge
maintainers:
- name: azrtydxb
  email: pascal@novaedge.io
icon: https://raw.githubusercontent.com/azrtydxb/novaedge/main/docs/logo.png
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: networking
