// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpfmesh

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type meshRedirectMeshSvcKey struct {
	_    structs.HostLayout
	Addr uint32
	Port uint16
	Pad  uint16
}

type meshRedirectMeshSvcValue struct {
	_            structs.HostLayout
	RedirectPort uint32
}

// loadMeshRedirect returns the embedded CollectionSpec for meshRedirect.
func loadMeshRedirect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MeshRedirectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load meshRedirect: %w", err)
	}

	return spec, err
}

// loadMeshRedirectObjects loads meshRedirect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*meshRedirectObjects
//	*meshRedirectPrograms
//	*meshRedirectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMeshRedirectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMeshRedirect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// meshRedirectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshRedirectSpecs struct {
	meshRedirectProgramSpecs
	meshRedirectMapSpecs
	meshRedirectVariableSpecs
}

// meshRedirectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshRedirectProgramSpecs struct {
	MeshRedirectProg *ebpf.ProgramSpec `ebpf:"mesh_redirect_prog"`
}

// meshRedirectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshRedirectMapSpecs struct {
	MeshRedirectStats *ebpf.MapSpec `ebpf:"mesh_redirect_stats"`
	MeshServices      *ebpf.MapSpec `ebpf:"mesh_services"`
	TproxySocket      *ebpf.MapSpec `ebpf:"tproxy_socket"`
}

// meshRedirectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshRedirectVariableSpecs struct {
}

// meshRedirectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMeshRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshRedirectObjects struct {
	meshRedirectPrograms
	meshRedirectMaps
	meshRedirectVariables
}

func (o *meshRedirectObjects) Close() error {
	return _MeshRedirectClose(
		&o.meshRedirectPrograms,
		&o.meshRedirectMaps,
	)
}

// meshRedirectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMeshRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshRedirectMaps struct {
	MeshRedirectStats *ebpf.Map `ebpf:"mesh_redirect_stats"`
	MeshServices      *ebpf.Map `ebpf:"mesh_services"`
	TproxySocket      *ebpf.Map `ebpf:"tproxy_socket"`
}

func (m *meshRedirectMaps) Close() error {
	return _MeshRedirectClose(
		m.MeshRedirectStats,
		m.MeshServices,
		m.TproxySocket,
	)
}

// meshRedirectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMeshRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshRedirectVariables struct {
}

// meshRedirectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMeshRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshRedirectPrograms struct {
	MeshRedirectProg *ebpf.Program `ebpf:"mesh_redirect_prog"`
}

func (p *meshRedirectPrograms) Close() error {
	return _MeshRedirectClose(
		p.MeshRedirectProg,
	)
}

func _MeshRedirectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed meshredirect_bpfel.o
var _MeshRedirectBytes []byte
