// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package xdplb

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdpLbBackendEntry struct {
	_    structs.HostLayout
	Addr uint32
	Port uint16
	Mac  [6]uint8
}

type xdpLbBackendListKey struct {
	_      structs.HostLayout
	ListId uint32
	Index  uint32
}

type xdpLbVipKey struct {
	_     structs.HostLayout
	Addr  uint32
	Port  uint16
	Proto uint8
	Pad   uint8
}

type xdpLbVipMeta struct {
	_             structs.HostLayout
	BackendCount  uint32
	BackendListId uint32
}

// loadXdpLb returns the embedded CollectionSpec for xdpLb.
func loadXdpLb() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpLbBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdpLb: %w", err)
	}

	return spec, err
}

// loadXdpLbObjects loads xdpLb and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpLbObjects
//	*xdpLbPrograms
//	*xdpLbMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpLbObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdpLb()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpLbSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpLbSpecs struct {
	xdpLbProgramSpecs
	xdpLbMapSpecs
	xdpLbVariableSpecs
}

// xdpLbProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpLbProgramSpecs struct {
	XdpLbProg *ebpf.ProgramSpec `ebpf:"xdp_lb_prog"`
}

// xdpLbMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpLbMapSpecs struct {
	BackendList *ebpf.MapSpec `ebpf:"backend_list"`
	LbStats     *ebpf.MapSpec `ebpf:"lb_stats"`
	VipBackends *ebpf.MapSpec `ebpf:"vip_backends"`
}

// xdpLbVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpLbVariableSpecs struct {
}

// xdpLbObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpLbObjects struct {
	xdpLbPrograms
	xdpLbMaps
	xdpLbVariables
}

func (o *xdpLbObjects) Close() error {
	return _XdpLbClose(
		&o.xdpLbPrograms,
		&o.xdpLbMaps,
	)
}

// xdpLbMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpLbMaps struct {
	BackendList *ebpf.Map `ebpf:"backend_list"`
	LbStats     *ebpf.Map `ebpf:"lb_stats"`
	VipBackends *ebpf.Map `ebpf:"vip_backends"`
}

func (m *xdpLbMaps) Close() error {
	return _XdpLbClose(
		m.BackendList,
		m.LbStats,
		m.VipBackends,
	)
}

// xdpLbVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpLbVariables struct {
}

// xdpLbPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpLbPrograms struct {
	XdpLbProg *ebpf.Program `ebpf:"xdp_lb_prog"`
}

func (p *xdpLbPrograms) Close() error {
	return _XdpLbClose(
		p.XdpLbProg,
	)
}

func _XdpLbClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdplb_bpfel.o
var _XdpLbBytes []byte
