/*
Copyright 2024 NovaEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package mesh provides east-west service mesh traffic interception using
// nftables/iptables NAT REDIRECT for transparent proxying of pod-to-pod traffic.
//
// # Why NAT REDIRECT instead of TPROXY
//
// We use NAT REDIRECT rather than TPROXY (transparent proxy) for traffic
// interception. This is a deliberate architectural choice with the following
// rationale:
//
// TPROXY (the iptables/nftables TPROXY target) intercepts packets without
// modifying them and assigns them directly to a listening socket via
// nf_tproxy_get_sock_v4(). While this avoids conntrack overhead, TPROXY
// has a critical compatibility limitation: it does not work reliably on
// bridge-based CNIs (Flannel, Calico, etc.) because the kernel's socket
// lookup in the TPROXY path fails to deliver packets to the TCP stack
// when traffic traverses a Linux bridge (e.g. cni0). In testing on
// k3s/Flannel, SYN packets matched TPROXY rules and reached INPUT with
// the correct fwmark, but no SYN-ACK was ever generated by the kernel.
//
// NAT REDIRECT rewrites the destination port to the local listener and
// creates a conntrack entry recording the original ClusterIP:port. The
// listener retrieves the original destination via getsockopt(SO_ORIGINAL_DST).
// Our REDIRECT chain runs at priority dstnat-1 (-101), which fires before
// kube-proxy's DNAT rules at priority dstnat (-100), ensuring the original
// ClusterIP is preserved in conntrack before kube-proxy can rewrite it.
//
// # Trade-offs
//
//   - Conntrack overhead: Each redirected connection creates a conntrack entry
//     (~300 bytes). In practice this is negligible because kube-proxy already
//     uses conntrack for all ClusterIP traffic -- our REDIRECT replaces
//     kube-proxy's DNAT entry rather than adding an extra one.
//
//   - Performance: The NAT rewrite is nanoseconds; the conntrack hash lookup
//     is O(1). No measurable difference vs TPROXY for real workloads.
//
//   - UDP mesh: REDIRECT relies on conntrack which has idle timeouts for UDP
//     flows. If UDP mesh support is added in the future, TPROXY or an
//     alternative mechanism (e.g. eBPF sk_lookup) should be evaluated for
//     UDP-specific interception.
//
//   - Socket transparency: With TPROXY, getsockname() returns the original
//     destination directly. With REDIRECT, SO_ORIGINAL_DST is required (which
//     we already use). No functional difference for our use case.
//
//   - CNI compatibility: REDIRECT works universally across all CNI plugins
//     and network topologies (bridge, veth, IPVLAN, etc.). TPROXY requires
//     specific kernel socket lookup behavior that varies by configuration.
//
// # Industry comparison
//
// NovaEdge's REDIRECT approach is consistent with the industry standard:
//
//   - Istio (sidecar mode): Uses iptables NAT REDIRECT as the default for
//     both inbound and outbound interception. TPROXY is available only for
//     inbound as a rarely-used opt-in. Uses SO_ORIGINAL_DST for original
//     destination recovery. No UDP mesh support.
//
//   - Istio (ambient mode / ztunnel): Uses TPROXY for inbound and REDIRECT
//     for outbound. Runs as a DaemonSet like NovaEdge. Still no UDP support
//     (HBONE tunnel is HTTP/2 over TCP).
//
//   - Linkerd: Uses iptables NAT REDIRECT exclusively. Explicitly rejected
//     TPROXY (github.com/linkerd/linkerd2/issues/7089) because it requires
//     CAP_NET_ADMIN on the proxy container. No UDP mesh support.
//
//   - Cilium: Uses eBPF hooks (TC, sock_ops, bpf_sk_assign) instead of
//     iptables entirely. Some TPROXY for L7 Envoy redirection, migrating
//     to pure eBPF. UDP is handled at L3/L4 only (load balancing + network
//     policy) -- no UDP mTLS or L7 proxying.
//
// No major service mesh supports UDP mTLS. It remains an unsolved problem
// because all tunnel protocols (HBONE, HTTP/2 CONNECT) are TCP-based. If
// NovaEdge adds UDP mesh support in the future, eBPF-based interception
// (bpf_sk_assign or sk_lookup) would be the recommended approach, as it
// avoids the conntrack limitations of REDIRECT for connectionless flows.
//
// # Architecture: host namespace vs pod namespace
//
// A key difference between NovaEdge and sidecar-based meshes (Istio sidecar,
// Linkerd) is where the interception rules live:
//
//   - Sidecar meshes inject iptables rules into each pod's network namespace
//     via an init container or CNI plugin. These rules fire in the pod's
//     OUTPUT chain before packets ever reach the host namespace. Because
//     kube-proxy's DNAT rules live in the host namespace, there is no
//     ordering conflict -- the sidecar REDIRECT captures the packet first.
//
//   - NovaEdge runs as a DaemonSet in the host network namespace. Our
//     REDIRECT rules and kube-proxy's DNAT rules are in the same namespace,
//     competing on the same PREROUTING chain. This is why we set our chain
//     priority to dstnat-1 (-101) to fire before kube-proxy's rules at
//     dstnat (-100), ensuring the original ClusterIP is preserved in
//     conntrack before kube-proxy can rewrite it to a pod IP.
//
// This host-namespace architecture is shared with Istio ambient mode
// (ztunnel) and Cilium, both of which face the same kube-proxy interaction
// challenge and solve it with priority ordering or eBPF bypass.
package mesh

import (
	"fmt"
	"sync"

	"go.uber.org/zap"
)

// RuleBackend abstracts the underlying packet-filtering system used for
// traffic interception (nftables or iptables). Both backends use NAT
// REDIRECT to rewrite the destination port to the local transparent
// listener. Implementations must be safe for sequential use but are
// always called under TPROXYManager's mutex.
type RuleBackend interface {
	// Setup initialises chains/tables needed for NAT REDIRECT interception.
	// It is called once before the first ApplyRules call.
	Setup() error

	// ApplyRules reconciles the set of intercepted targets so that, after
	// the call returns, only the given targets are matched. The nftables
	// backend applies changes atomically via a single netlink batch; the
	// iptables backend applies per-rule changes and may partially fail
	// (errors are aggregated and returned).
	ApplyRules(targets []InterceptTarget, tproxyPort int32) error

	// Cleanup removes all rules, chains/tables, and routing entries
	// created by Setup/ApplyRules.
	Cleanup() error

	// Name returns a human-readable backend identifier (e.g. "nftables").
	Name() string
}

// InterceptTarget represents a ClusterIP:port to intercept.
type InterceptTarget struct {
	ClusterIP string
	Port      int32
}

// Key returns a unique key for this target.
func (t InterceptTarget) Key() string {
	return fmt.Sprintf("%s:%d", t.ClusterIP, t.Port)
}

// TPROXYManager manages NAT REDIRECT rules for intercepting east-west
// traffic destined to Kubernetes ClusterIP Services. It delegates the
// actual packet-filter manipulation to a RuleBackend (nftables or iptables).
//
// The name "TPROXY" is retained for historical reasons and code
// compatibility; the actual interception mechanism is NAT REDIRECT
// (see package-level documentation for the rationale).
type TPROXYManager struct {
	mu          sync.Mutex
	logger      *zap.Logger
	backend     RuleBackend
	tproxyPort  int32
	intercepted map[string]InterceptTarget // key: "clusterIP:port"
}

// NewTPROXYManager creates a new TPROXY rule manager using auto-detected
// backend (nftables preferred, iptables fallback).
// tproxyPort is the local port where the transparent listener accepts connections.
func NewTPROXYManager(logger *zap.Logger, tproxyPort int32) *TPROXYManager {
	named := logger.Named("tproxy")
	backend := detectBackend(named)
	named.Info("Selected TPROXY backend", zap.String("backend", backend.Name()))
	return &TPROXYManager{
		logger:      named,
		backend:     backend,
		tproxyPort:  tproxyPort,
		intercepted: make(map[string]InterceptTarget),
	}
}

// NewTPROXYManagerWithBackend creates a TPROXY manager with an explicit
// backend (for testing or manual override).
func NewTPROXYManagerWithBackend(logger *zap.Logger, tproxyPort int32, backend RuleBackend) *TPROXYManager {
	return &TPROXYManager{
		logger:      logger.Named("tproxy"),
		backend:     backend,
		tproxyPort:  tproxyPort,
		intercepted: make(map[string]InterceptTarget),
	}
}

// Setup initializes the backend (chains/tables and routing rules).
// Must be called before ApplyRules.
func (m *TPROXYManager) Setup() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if err := m.backend.Setup(); err != nil {
		return fmt.Errorf("TPROXY backend setup failed (%s): %w", m.backend.Name(), err)
	}
	return nil
}

// ApplyRules reconciles TPROXY rules to match the desired set of
// intercepted ClusterIP:port pairs.
func (m *TPROXYManager) ApplyRules(desired []InterceptTarget) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if err := m.backend.ApplyRules(desired, m.tproxyPort); err != nil {
		return fmt.Errorf("TPROXY apply rules failed (%s): %w", m.backend.Name(), err)
	}

	// Rebuild the intercepted map for tracking/logging.
	m.intercepted = make(map[string]InterceptTarget, len(desired))
	for _, t := range desired {
		m.intercepted[t.Key()] = t
	}

	m.logger.Info("TPROXY rules reconciled",
		zap.Int("active_rules", len(m.intercepted)),
		zap.String("backend", m.backend.Name()))
	return nil
}

// Cleanup removes all TPROXY rules and routing entries.
func (m *TPROXYManager) Cleanup() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if err := m.backend.Cleanup(); err != nil {
		m.logger.Error("TPROXY cleanup failed",
			zap.String("backend", m.backend.Name()),
			zap.Error(err))
		return err
	}

	m.intercepted = make(map[string]InterceptTarget)
	m.logger.Info("TPROXY cleanup complete", zap.String("backend", m.backend.Name()))
	return nil
}

// ActiveRuleCount returns the number of active TPROXY rules.
func (m *TPROXYManager) ActiveRuleCount() int {
	m.mu.Lock()
	defer m.mu.Unlock()
	return len(m.intercepted)
}
